name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd CoinBook; swift build -v
#    - name: Run tests
#      run: cd CoinBook; swift test -v
